body/urls.py
from django.urls import path
from .views import *

app_name = "body"

urlpatterns = [
    path('', welcome, name="welcome"),
    path('home/', home, name='home'),
    path('add_person/', add_person, name='add_person'),
    path('reviews/', reviews, name='reviews'),
    path('add_review/', add_review, name='add_review'),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("body.urls")),
    path('user/', include("users.urls")),
] 
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

body/models.py
from django.db import models
from django.conf import settings
from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
import sys
from django.core.validators import MaxValueValidator, MinValueValidator



User = settings.AUTH_USER_MODEL


# Create your models here.
class Person(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_bodies')
    full_name = models.CharField(max_length=200)
    photo = models.ImageField(upload_to='photos')
    phone = models.CharField(max_length=200)
    age = models.IntegerField(default=18)
    location = models.CharField(max_length=200)
    pub_date = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0, validators=[
                                   MaxValueValidator(5),
                                   MinValueValidator(0) 
                                ])

    class Meta:
        ordering = ['-id']
        verbose_name = 'Person'

    
    def __str__(self):
        return str(self.full_name)

    def save(self, *args, **kwargs):
        # Opening the uploaded image
        img = Image.open(self.photo)

        if img.height > 200 or img.width > 200:

            output_size = (200, 200)
            img.thumbnail(output_size)
            img = img.convert('RGB')

            output = BytesIO()
            img.save(output, format='JPEG')
            output.seek(0)

            # change the photofield value to be the newley modifed photo value
            self.photo = InMemoryUploadedFile(output, 'ImageField',
                                            f'{self.photo.name.split(".")[0]}.jpg',
                                            'image/jpeg', sys.getsizeof(output),
                                            None)

        super().save(*args, **kwargs)

class Review(models.Model):
    user =  models.ForeignKey(User, models.SET_NULL, blank=True, null=True, related_name="user_reviews")
    username = models.CharField(max_length=200, null=True, blank=True)
    review_text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)


    class Meta:
        ordering = ['-id']
        verbose_name = 'Review'


    def __str__(self):
        return str(self.user.username)    

body/forms.py
from .models import Person, Review
from django.forms import ModelForm

# model forms
class PersonForm(ModelForm):
    class Meta:
        model = Person
        fields = "__all__"
        exclude = ['user', 'pub_date', 'rating']

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['review_text']

body/views.py
import logging
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from .models import Person, Review
from .forms import PersonForm, ReviewForm
from users.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.core import serializers
from django.contrib.auth import get_user_model
from django.utils import timezone

logger = logging.getLogger(__name__)

User = get_user_model()

"""
    Landing page also has sign up form
"""
# home view
def welcome(request):

    if request.user.is_authenticated:
        return redirect('body:home')

    form = UserCreationForm()
    
    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'

    if request.method == 'POST' and is_ajax:
        form = UserCreationForm(request.POST)        
        email = request.POST['email']
        username = request.POST['username']
        password = request.POST['password1']

        if form.is_valid():
            form.save()
            total_users = User.objects.all().count()
            logger.info(f"[ User {total_users}] email :- {email} username :- {username}")
            user = authenticate(email=email, password=password)
            if user is not None:
                login(request, user)
                return JsonResponse({"message":"User created successfully"}, status = 200)
        return JsonResponse({"message": "Invalid form"}, status=400)
        
    context = {"form": form} 

    # request.session.set_test_cookie()
   
    return render(request, 'welcome.html', context)

"""
    Home page displays all bodies that have been added
"""
    
@login_required
def home(request):  
    form = PersonForm()
        
    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'

    if request.method == 'GET' and is_ajax:
        persons_list = list(Person.objects.filter(user=request.user).values())
        return JsonResponse({"persons_list": persons_list}, status = 200)

    return render(request, 'body/home.html', {"form": form})

# add body
@login_required
def add_person(request):
    
    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'

    if request.method == 'POST' and is_ajax:
        form = PersonForm(request.POST, request.FILES)
        if form.is_valid():
            user = request.user
            new_person = Person.objects.create(
                user=user,
                full_name=request.POST['full_name'],
                photo=request.FILES['photo'],                
                phone=request.POST['phone'],                
                age=request.POST['age'],                
                location=request.POST['location'], 
                rating = request.POST['rating']    
            )
            person = serializers.serialize("json", [new_person,])
            return JsonResponse({"person":  person}, status=200, safe=False)
        return JsonResponse({"message":"Invalid form data"}, status=400)
    return JsonResponse({"message":"Invalid request"}, status=400)


# review views
def reviews(request):
    form = ReviewForm()
        
    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'

    if request.method == 'GET' and is_ajax:        
        review_list = list(Review.objects.all().values())
        total_reviews = Review.objects.all().count()

        return JsonResponse({
            'review_list':review_list,
            "total_reviews":total_reviews
        }, status = 200)

    return render(request, 'body/reviews.html', {"form": form})

@login_required
def add_review(request):
    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'

    if request.method == 'POST' and is_ajax: 
        form = ReviewForm(request.POST)
        if form.is_valid():                               
            new_review = Review.objects.create(user=request.user, review_text=request.POST['review_text'], username=request.user.username )
            review = serializers.serialize('json', [new_review,])
            return JsonResponse({"review":review}, status = 200)
        return JsonResponse({"message":"Invalid form data"}, status=400)
    return JsonResponse({"message":"Invalid request"}, status=400)


templates/body/home.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Home{% endblock title %}

<!-- content block -->
{% block content %}
    <section class='container'>
        <!-- add bodycount button -->
        <div class="text-center">
            <!-- <button class="my-3 fs-6 fw-bold text-capitalize py-1 px-3 my-btn">Add new</button> -->
            <button type="button"  class='shell-btn px-4 mb-3' data-bs-toggle="modal" data-bs-target="#addPersonModal">
                Add new
            </button>
        </div>
        
        <!-- Modal -->
        <div class="modal fade" id="addPersonModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="addPersonModalLabel" aria-hidden="true">
            <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-body">
                    <form class="row g-3" id='form' action="" enctype="multipart/form-data">
                      {% csrf_token %}

                      <div class="col-md-6">
                        <label for="full_name" class="form-label">Full Name</label>
                        {{ form.full_name|add_class:"form-control" }}
                      </div>

                      <div class="col-md-6">
                        <label for="phone" class="form-label">Phone</label>
                        {{ form.phone|add_class:"form-control" }}                        
                      </div>

                      <div class="col-12">                            
                        <label for="photo" class="form-label">Upload Photo</label>
                        {{ form.photo|add_class:"form-control" }}
                      </div>

                      <div class="col-md-4">
                        <label for="age" class="form-label">Age</label>
                        {{ form.age|add_class:"form-control" }}
                      </div>

                      <div class="col-md-4">
                        <label for="location" class="form-label">Location/Town</label>
                        {{ form.location|add_class:"form-control" }}
                      </div>

                      <div class="col-md-4">
                        <label for="rating" class="form-label">Rating</label>
                        <div class='stars'>
                          <span id='1' class="fa fa-star"></span>
                          <span id='2' class="fa fa-star"></span>
                          <span id='3' class="fa fa-star"></span>
                          <span id='4' class="fa fa-star"></span>
                          <span id='5' class="fa fa-star"></span>
                        </div>
                      </div>

                      <div class="d-grid gap-2 mb-3">
                        <button type="submit" id='submit' class="btn btn-sm btn-secondary rounded-0 fw-bold">Add</button>
                      </div>

                    </form>
                    <div class="d-grid gap-2">
                    <button type="button" class="btn-main" data-bs-dismiss="modal">Cancel</button>
                    </div>

              </div>
            </div>
            </div>
        </div>
        <!-- list all persons-->
        <section id="content" class='mb-5'>
        </section>
         

    </section>
{% endblock content %}



{% block javascript %}
<script>
  // handle rating
  const one = document.getElementById("1")
  const two = document.getElementById("2")
  const three = document.getElementById("3")
  const four = document.getElementById("4")
  const five = document.getElementById("5")

  const handleStartSelect = (size)=> {
    const all_stars = document.querySelector(".stars").children;
    for (let i=0; i < all_stars.length; i++) {
        if(i<=size){
          all_stars[i].classList.add("checked");
        } else {
          all_stars[i].classList.remove("checked");          
        }
    }
  }

  const handleSelect = (selection)=> {
    switch(selection){
      case 1: {
        handleStartSelect(0)
        return
      }
      case 2: {
        handleStartSelect(1)
        return
      }

      case 3: {
        handleStartSelect(2)
        return
      }

      case 4: {
        handleStartSelect(3)
        return
      }

      case 5: {
        handleStartSelect(4)
        return
      }
      
    }
  }

  const all_stars = [one, two, three, four, five]

  let vote_star = 0;

  all_stars.forEach(item => {
    item.addEventListener('mouseover', (event)=> {
      handleSelect(parseInt(event.target.id))
    })

    item.addEventListener('click', (event)=>{
      vote_star = parseInt(event.target.id)
    })
  })


  // when document is ready get persons list
  $(document).ready(function(){
        $("#form input").prop("required", true)
        // add class to home tag
        $("body").addClass("home")
        $("#nav-home").addClass('active')
        // insert a loader or spinner
        $("#content").html(
          `
          <div class="spinner-border" style="width: 5rem; height: 5rem;" role="status"></div>
          `
        )

            // get coookies
            function getCookie(name) {
              let cookieValue = null;
              if (document.cookie && document.cookie !== '') {
                  const cookies = document.cookie.split(';');
                  for (let i = 0; i < cookies.length; i++) {
                      const cookie = cookies[i].trim();
                      // Does this cookie string begin with the name we want?
                      if (cookie.substring(0, name.length + 1) === (name + '=')) {
                          cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                          break;
                      }
                  }
              }
              return cookieValue;
          }
          const csrftoken = getCookie('csrftoken');
          
          $.ajax({
              url:"{% url 'body:home' %}",
              type: "GET",
              processData: false,
              contentType: false,
              headers: {
                  "X-Requested-With": "XMLHttpRequest",
                  'X-CSRFToken': csrftoken
              },
              success: (response)=> {
                $(".spinner-border").remove()
                if (response.persons_list.length == 0) {
                  $("#content").append("<p class='none text-center'>You haven't added a peson you banged !! </p>")
                } 

                if (response.persons_list.length >= 0) {
                  response.persons_list.forEach((person)=> {
                    const stars = (count)=> {
                      switch(count){
                        case 0: {
                         return `
                        <span class="fa fa-star"></span>
                        <span class="fa fa-star"></span>
                        <span class="fa fa-star"></span>
                        <span class="fa fa-star"></span>
                        <span class="fa fa-star"></span>
                        `
                        }
                        case 1:{
                        return `
                        <span class="fa fa-star checked"></span>
                        <span class="fa fa-star"></span>
                        <span class="fa fa-star"></span>
                        <span class="fa fa-star"></span>
                        <span class="fa fa-star"></span>
                        `
                        }
                        case 2: {
                        return `
                        <span class="fa fa-star checked"></span>
                        <span class="fa fa-star checked"></span>
                        <span class="fa fa-star"></span>
                        <span class="fa fa-star"></span>
                        <span class="fa fa-star"></span>
                        `
                        }
                        case 3: {
                        return `
                        <span class="fa fa-star checked"></span>
                        <span class="fa fa-star checked"></span>
                        <span class="fa fa-star checked"></span>
                        <span class="fa fa-star "></span>
                        <span class="fa fa-star "></span>
                        `
                        }
                        case 4: {
                        return `
                        <span class="fa fa-star checked"></span>
                        <span class="fa fa-star checked"></span>
                        <span class="fa fa-star checked"></span>
                        <span class="fa fa-star checked"></span>
                        <span class="fa fa-star"></span>
                        `
                        }
                        case 5: {
                        return `
                        <span class="fa fa-star checked"></span>
                        <span class="fa fa-star checked"></span>
                        <span class="fa fa-star checked"></span>
                        <span class="fa fa-star checked"></span>
                        <span class="fa fa-star checked"></span>
                        `
                        }
                      }
                    }
                    var person_card = `
                    <div class="person-card">
                      <div class="card-content">
                        <img src="/media/${person.photo}" alt="${person.full_name}" />
                          <div class='mt-2'>
                              <p class="m-0"><span>age: </span>${person.age} </p>
                              <p class="m-0"><span>Town: </span>${person.location} </p>
                              <p class="m-0"> <span>Phone: </span> ${person.phone} </p>
                              <p class="m-0"> <span>Rating: </span> ${stars(person.rating)}</p>
                              <h5 class='text-center mt-2'> ${person.full_name} </h5>
                          </div>
                      </div
                  </div>                    
                    `
                  $("#content").append(person_card)

                  })


                }
              },
              error: (error)=> {
                  console.log(error.message)
              }
          })
  })
  // on submit call this function
    $("#form").submit(function(e){
        e.preventDefault();

        $("#submit").text("Adding ...")
        $("#submit").prop("disabled", true)

        let data = new FormData($(this).get(0))
        data.append('rating',vote_star)

        // get coookies
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getCookie('csrftoken');
        
        $.ajax({
            url:"{% url 'body:add_person' %}",
            type: "POST",
            processData: false,
            contentType: false,
            headers: {
                "X-Requested-With": "XMLHttpRequest",
                'X-CSRFToken': csrftoken
            },
            data: data,
            success: (response)=> {
              
              if ($(".none")){
                $(".none").remove()
              }

              $(".modal").modal("hide");
              // create new toast element
              const new_person = JSON.parse(response.person)[0].fields
              $("#content").prepend( 
                  `
                  <div class="person-card">
                    <div class="card-content">
                      <img src="/media/${new_person.photo}" alt="${new_person.full_name}" />
                      <div class='mt-2'>
                        <p class="m-0"><span>age: </span>${person.age} </p>
                        <p class="m-0"><span>Town: </span>${person.location} </p>
                        <p class="m-0"> <span>Phone: </span> ${person.phone} </p>
                        <p class="m-0"> <span>Rating: </span> ${stars(person.rating)}</p>
                        <h5 class='text-center mt-2'> ${person.full_name} </h5>
                    </div>
                    </div
                </div>                    
                `
              )


            },
            error: (error)=> {
                console.log(error.responseJSON.message)
            }
        })
    })
</script>
{% endblock javascript %}

templates/body/reviews.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Reviews{% endblock title %}

{% block content %}
<section class="container">
    <!-- posted reviews total in number post review -->
    <section class='text-center  my-4 py-4'>
        <h6 class="fw-bold"><span id='count'></span>
            Review(s) posted.
            <button class="btn btn-link btn-sm" type="button" data-bs-toggle="collapse" data-bs-target="#postReviewCollapse" aria-expanded="false" aria-controls="postReviewCollapse">
                Post your review
              </button>
        </h6>

        <div class="collapse" id="postReviewCollapse">
            <div class="card card-body">
                <form  method='post' action="" id="form" >
                    {% csrf_token %}
                    {{ form.review_text|add_class:"form-control" }}
                    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                        <button type="submit" id='post' class="btn btn-sm btn-primary py-1 px-3 mt-3 me-md-2">Post Review</button>   

                      </div>
                </form>
            </div>
        </div>
          
    </section>
    <!-- review list -->
    <section id='reviews'>


    </section>

</section>
{% endblock content %}



{% block javascript %}
<script>
    // on load show a toast
    $(document).ready(function(){
        $("body").addClass("review")
        $(".form-control").prop("placeholder", "Post your thoughts ...")
        $("#nav-reviews").addClass('active')
        $("#reviews").html(
            `
            <div class='text-center loader'><div class="spinner-border" style="width: 4rem; height: 4rem;" role="status"></div></div>
            `
          )
                // get coookies
                function getCookie(name) {
                    let cookieValue = null;
                    if (document.cookie && document.cookie !== '') {
                        const cookies = document.cookie.split(';');
                        for (let i = 0; i < cookies.length; i++) {
                            const cookie = cookies[i].trim();
                            // Does this cookie string begin with the name we want?
                            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                                break;
                            }
                        }
                    }
                    return cookieValue;
                }
                const csrftoken = getCookie('csrftoken');
                
                $.ajax({
                    url:"{% url 'body:reviews' %}",
                    type: "GET",
                    processData: false,
                    contentType: false,
                    headers: {
                        "X-Requested-With": "XMLHttpRequest",
                        'X-CSRFToken': csrftoken
                    },
                    success: (response)=> {
                        $(".loader").remove()
                        const reviews = response.review_list
                        const total_reviews = response.total_reviews
                        if (reviews.length == 0) {
                            $("#count").text('0')

                            $("#reviews").append(`
                                <p class="none text-center mt-3">No reviews have been posted. </p>
                                
                            `)                            
                        }
                        if (reviews.length >= 0) {
                            reviews.forEach((review)=> {
                                $("#count").text(`${total_reviews}`)

                                $("#reviews").append(`
                                    <div class="pe-auto shadow-sm w-75 p-3 mb-5 bg-body rounded">
                                        <p class="m-1 px-2 border-start border-warning border-3 rounded-start">${review.review_text} </p>
                                        <p class="blockquote-footer text-end m-0 mt-1">${review.username}</p> 
                                    </div>
                                `) 
                            })
                        }
                    },
                    error: (error)=> {
                        console.log(error.message)
                    }
                })
    })
    // submit review function
    $("#form").submit(function(e){
        e.preventDefault();
        $("#post").text("Posting ...")
        $("#post").prop("disabled", true)

        let data = new FormData($(this).get(0))

        // get coookies
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getCookie('csrftoken');
        
        $.ajax({
            url:"{% url 'body:add_review' %}",
            type: "POST",
            processData: false,
            contentType: false,
            headers: {
                "X-Requested-With": "XMLHttpRequest",
                'X-CSRFToken': csrftoken
            },
            data: data,
            success: (response)=> {
                
                $("#post").text("Post Review")
                $("#post").prop("disabled", false)
                
                if ($(".none")){
                    $(".none").remove()
                  }

                const review_data = JSON.parse(response.review)[0].fields
                
                $("#postReviewCollapse").collapse('hide')
                
                $("#reviews").prepend(`
                <div class="pe-auto shadow-sm w-75 p-3 mb-5 bg-body rounded">
                    <p class="m-1 px-2 border-start border-warning border-3 rounded-start">${review_data.review_text}</p>
                    <p class="blockquote-footer text-end m-0 mt-1">${review_data.username}</p> 
                </div>
                `) 
            },
            error: (error)=> {
                console.log(error.message)                
                $("#post").text("Post Review")
                $("#post").prop("disabled", false)
            }
        })
    })
</script>
{% endblock javascript %}