body/urls.py
from django.urls import path
from .views import *

app_name = "body"

urlpatterns = [
    path('', welcome, name="welcome"),
    path('home/', home, name='home'),
    path('add_person/', add_person, name='add_person'),
    path('reviews/', reviews, name='reviews'),
    path('add_review/', add_review, name='add_review'),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("body.urls")),
    path('user/', include("users.urls")),
] 
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views
from .views import *

app_name = 'users'

urlpatterns = [
    # path('registration/', registration, name='registration'),
    path('signin/', signin, name='signin'),
    path('signout/', signout, name='signout'),
    path('view_profile/', view_profile, name='view_profile'),
    path('edit_profile/', edit_profile, name='edit_profile'),
    path('close_account/', close_account, name='close_account'),
    
    # check username and mail
    path('check_mail/', check_mail, name='check_mail'),
    path('check_username/', check_username, name='check_username'),

    # password change
    path(
        "password_change/", views.PasswordChangeView.as_view(
            template_name = "users/password_change_form.html",
            success_url = reverse_lazy("users:password_change_done")
            ), 
            name="password_change"
    ),
    path(
        "password_change/done/",
        views.PasswordChangeDoneView.as_view(template_name = "users/password_change_done.html"),
        name="password_change_done",
    ),

    # password reset
    path("password_reset/", views.PasswordResetView.as_view(
            template_name = "users/password_reset.html",
            success_url = reverse_lazy("users:password_reset_done"),
            email_template_name = "users/password_reset_email.html"
            ), 
        name="password_reset"
    ),
    path("password_reset/done/", views.PasswordResetDoneView.as_view(template_name = "users/password_reset_done.html"), name="password_reset_done"),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(
            template_name = "users/password_reset_confirm.html",
            success_url = reverse_lazy("users:password_reset_complete")
            
        ),
        name="password_reset_confirm",
    ),
    path("reset/done/", views.PasswordResetCompleteView.as_view(template_name = "users/password_reset_complete.html"), name="password_reset_complete")
    ] 

templates/includes/header.html
<!-- header or navbar -->

<header class="py-1">
    <nav class="container navbar my-nav fs-5 fw-bold">
        <div class="mb-2 text-center">
          <a class="navbar-brand" href="{% url 'body:home' %}">Track Bodycount</a>
        </div>

        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" id='nav-home' href="{% url 'body:home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id='nav-reviews' href="{% url 'body:reviews' %}">Reviews</a>
            </li>
            
            {% if request.user.is_authenticated %}
            <div class="btn-group">
                <button type="button" class="btn p-0 px-3 fw-bold btn-sm btn-outline-secondary">Settings</button>
                <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle dropdown-toggle-split" id="dropdownMenuReference" data-bs-toggle="dropdown" aria-expanded="false" data-bs-reference="parent">
                  <span class="visually-hidden">Toggle Dropdown</span>
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuReference">
                  <li><a class="dropdown-item" href="{% url 'users:view_profile' %}">Profile</a></li>
                  <li><a class="dropdown-item" href="{% url 'users:signout' %}">Sign Out</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'users:password_change' %}">Change password</a></li>
                  <li><a class="dropdown-item" href="{% url 'users:close_account' %}">Close account</a></li>
                </ul>
              </div>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" id='nav-signin' href="{% url 'users:signin' %}">Sign In</a>
            </li>
            {% endif %}
    </nav>
    
</header>
