body/urls.py
from django.urls import path
from .views import *

app_name = "body"

urlpatterns = [
    path('', welcome, name="welcome"),
    path('home/', home, name='home'),
    path('add_person/', add_person, name='add_person'),
    path('reviews/', reviews, name='reviews'),
    path('add_review/', add_review, name='add_review'),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("body.urls")),
    path('user/', include("users.urls")),
] 
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views
from .views import *

app_name = 'users'

urlpatterns = [
    # path('registration/', registration, name='registration'),
    path('signin/', signin, name='signin'),
    path('signout/', signout, name='signout'),
    path('view_profile/', view_profile, name='view_profile'),
    path('edit_profile/', edit_profile, name='edit_profile'),
    path('close_account/', close_account, name='close_account'),
    
    # check username and mail
    path('check_mail/', check_mail, name='check_mail'),
    path('check_username/', check_username, name='check_username'),

    # password change
    path(
        "password_change/", views.PasswordChangeView.as_view(
            template_name = "users/password_change_form.html",
            success_url = reverse_lazy("users:password_change_done")
            ), 
            name="password_change"
    ),
    path(
        "password_change/done/",
        views.PasswordChangeDoneView.as_view(template_name = "users/password_change_done.html"),
        name="password_change_done",
    ),

    # password reset
    path("password_reset/", views.PasswordResetView.as_view(
            template_name = "users/password_reset.html",
            success_url = reverse_lazy("users:password_reset_done"),
            email_template_name = "users/password_reset_email.html"
            ), 
        name="password_reset"
    ),
    path("password_reset/done/", views.PasswordResetDoneView.as_view(template_name = "users/password_reset_done.html"), name="password_reset_done"),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(
            template_name = "users/password_reset_confirm.html",
            success_url = reverse_lazy("users:password_reset_complete")
            
        ),
        name="password_reset_confirm",
    ),
    path("reset/done/", views.PasswordResetCompleteView.as_view(template_name = "users/password_reset_complete.html"), name="password_reset_complete")
    ] 

users/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from django.conf import settings
# from django_cryptography.fields import encrypt
from .choices import SEX_CHOICES


# Create your models here.

User = settings.AUTH_USER_MODEL

class MyUserManager(BaseUserManager):
    def create_user(self, email, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    username = models.CharField(
        max_length=255,
        unique=True
    )
    joined_date = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField()
    username = models.CharField(max_length=100, unique=True)
    age = models.CharField(default='18', max_length=10)
    gender = models.CharField(max_length=20, choices=SEX_CHOICES, default="Male")

    def __str__(self):
        return self.username

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link type="text/css" rel="stylesheet" href="{% static 'css/main.css' %}">
    <!-- title block -->
    <title>Body count - {% block title %}{% endblock title %}</title>
</head>

<body>

    <!-- include header -->
    {% include 'includes/header.html' %}

    <!-- content block -->
    {% block content %} 
    {% endblock content %}

    <!-- include footer -->

    <!-- loading jquery -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    {% block javascript %}
    {% endblock javascript %}
</body>
</html>

templates/welcome.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Welcome{% endblock title %}
<!-- attaching block content -->
{% block content %}
    <section class="container mt-3">
        <!-- alert toast -->
        <div aria-live="polite" aria-atomic="true" class="position-relative">
            <div class="toast-container position-absolute top-0 end-0 p-3">
          
              <!-- Then put toasts within -->
              <div class="toast align-items-center text-white bg-warning" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="d-flex">
                  <div class="toast-body"></div>
                  <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
              </div>

            </div>
          </div>

        <div class='row row-cols-lg-2 welcome-container'>
            <!-- welcome message -->
            <div class="col text-center">
                <h4 class="my-4 text-capitalize" >Welcome</h4>
                <p>I help humans with high sex drive like myself, who loves having sex with diffrent humans, to track their bodycounts.</p>
                <p>Personally I lost track of my bodycount which is sad, so I decided to make this web app to help my fellow humans not lose track of their bodycount.</p>
            </div>
            <!-- sign up form -->
            <div class="col">
                <form class="form-content" id='form' action="">
                    {% csrf_token %}
                    <p class="text-center m-0 py-2 fs-4 fw-bold mb-3">Welcome don't be shy</p>

                    <div class='mb-3' >
                        <label for="username">Username</label>
                        {{form.username|add_class:"form-control"}}
                        <p class='username-error fs-6 mt-1 text-danger'></p>
                    </div>
                    
                    <div class='mb-3' >
                        <label for="email">Email</label>
                        {{form.email|add_class:"form-control"}}
                        <p class='email-error fs-6 mt-1 text-danger'></p>
                    </div>
                    
                    <div class='mb-3' >
                        <label for="password1">Password</label>
                        {{form.password1|add_class:"form-control"}}

                    </div>
        
                    <div class='mb-3' >
                        <label for="password2">Confirm Password</label>
                        {{form.password2|add_class:"form-control"}}

                    </div>
                    
                    <div class='d-grid gap-2 mt-3'>
                        <button type="submit" id='submit' class=" btn-main py-1 px-3">Sign Up</button>
                    </div>
                </form>
                
                <p class='text-center mt-3'>have an account <a href="{% url 'users:signin' %}">login</a></p>

            </div>

        </div>
        
    </section>
{% endblock content %} 


{% block javascript %}
<script>
    // when ready
    $(document).ready(function(){
        $("body").addClass("welcome")
    })

    // email key up
    $("#id_email").focusout(function(e){
        const data = {"email":e.target.value}

        // get coookies
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getCookie('csrftoken');
        
        $.ajax({
            url:"{% url 'users:check_mail' %}",
            type: "POST",
            processData: false,
            contentType: false,
            headers: {
                "X-Requested-With": "XMLHttpRequest",
                'X-CSRFToken': csrftoken
            },
            data: JSON.stringify(data),
            success: (response)=> {
                if (response.valid) {
                    $(".email-error").text("email exists")
                }
            },
            error: (error)=> {
                console.log(error.message)
            }
        })
    })

    // clear email warning
    $("#id_email").focusin(function(e){
        $(".email-error").text("")
    });

    // username
    $("#id_username").focusout(function(e){
        const data = {"username":e.target.value}

        // get coookies
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getCookie('csrftoken');
        
        $.ajax({
            url:"{% url 'users:check_username' %}",
            type: "POST",
            processData: false,
            contentType: false,
            headers: {
                "X-Requested-With": "XMLHttpRequest",
                'X-CSRFToken': csrftoken
            },
            data: JSON.stringify(data),
            success: (response)=> {
                if (response.valid) {
                    $(".username-error").text("username exists")
                }
            },
            error: (error)=> {
                console.log(error.message)
            }
        })
        
    })

    // clear email warning
    $("#id_username").focusin(function(e){
        $(".username-error").text("")
    }); 
    // Registering user
    $("#form").submit(function(e){
        e.preventDefault();


        let data = new FormData($(this).get(0))


        // get coookies
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getCookie('csrftoken');

        // counter check if password before submitting
        const password1 = $("#id_password1").val()
        const password2 = $("#id_password2").val()

        if (password1 === password2) {            

            $("#submit").text("Registering ...")
            $("#submit").prop('disabled',true)
            
            $.ajax({
                url:"{% url 'body:welcome' %}",
                type: "POST",
                processData: false,
                contentType: false,
                headers: {
                    "X-Requested-With": "XMLHttpRequest",
                    'X-CSRFToken': csrftoken
                },
                data: data,
                success: (response)=> {
                    console.log(response.message)
                    window.location.href = 'home/'
                },
                error: (error)=> {
                    console.log(error.message)
                }
            });
        } else {
            $(".toast-body").text("Password don't match")
            $(".toast").toast("show")

        }
    })
</script>
{% endblock javascript %}

templates/welcomePage.html
{% extends "base.html" %}
{% load static %}

<!-- attaching block content -->
{% block content %}
    <section class="container mt-5 text-center">
        <!-- welcome message -->
        <div class="my-4">
            <h4 class="my-4 text-capitalize" >Welcome</h4>
            <p>I help humans with high sex drive like myself, who loves having sex with diffrent humans, to track their bodycounts.</p>
            <p>Personally I lost track of my bodycount which is sad, so I decided to make this web app to help my fellow humans not lose track of their bodycount.</p>
        </div>
        <!-- sign up and sign in buttons -->
        <button class="my-btn py-1 px-3 mx-3">Sign Up</button>
        <p class="mt-2 text-center text-muted">Don't be ashamed !!!!!</p>
    </section>
{% endblock content %}