body/urls.py
from django.urls import path
from .views import *

app_name = "body"

urlpatterns = [
    path('', welcome, name="welcome"),
    path('home/', home, name='home'),
    path('add_person/', add_person, name='add_person'),
    path('reviews/', reviews, name='reviews'),
    path('add_review/', add_review, name='add_review'),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("body.urls")),
    path('user/', include("users.urls")),
] 
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views
from .views import *

app_name = 'users'

urlpatterns = [
    # path('registration/', registration, name='registration'),
    path('signin/', signin, name='signin'),
    path('signout/', signout, name='signout'),
    path('view_profile/', view_profile, name='view_profile'),
    path('edit_profile/', edit_profile, name='edit_profile'),
    path('close_account/', close_account, name='close_account'),
    
    # check username and mail
    path('check_mail/', check_mail, name='check_mail'),
    path('check_username/', check_username, name='check_username'),

    # password change
    path(
        "password_change/", views.PasswordChangeView.as_view(
            template_name = "users/password_change_form.html",
            success_url = reverse_lazy("users:password_change_done")
            ), 
            name="password_change"
    ),
    path(
        "password_change/done/",
        views.PasswordChangeDoneView.as_view(template_name = "users/password_change_done.html"),
        name="password_change_done",
    ),

    # password reset
    path("password_reset/", views.PasswordResetView.as_view(
            template_name = "users/password_reset.html",
            success_url = reverse_lazy("users:password_reset_done"),
            email_template_name = "users/password_reset_email.html"
            ), 
        name="password_reset"
    ),
    path("password_reset/done/", views.PasswordResetDoneView.as_view(template_name = "users/password_reset_done.html"), name="password_reset_done"),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(
            template_name = "users/password_reset_confirm.html",
            success_url = reverse_lazy("users:password_reset_complete")
            
        ),
        name="password_reset_confirm",
    ),
    path("reset/done/", views.PasswordResetCompleteView.as_view(template_name = "users/password_reset_complete.html"), name="password_reset_complete")
    ] 

users/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from django.conf import settings
# from django_cryptography.fields import encrypt
from .choices import SEX_CHOICES


# Create your models here.

User = settings.AUTH_USER_MODEL

class MyUserManager(BaseUserManager):
    def create_user(self, email, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    username = models.CharField(
        max_length=255,
        unique=True
    )
    joined_date = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField()
    username = models.CharField(max_length=100, unique=True)
    age = models.CharField(default='18', max_length=10)
    gender = models.CharField(max_length=20, choices=SEX_CHOICES, default="Male")

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from .models import Profile
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import ReadOnlyPasswordHashField, AuthenticationForm

User = get_user_model()

class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Password confirmation", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'username' )
    
    def clean_password2(self):
        # check that password match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Password does not match")
        return password2
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data.get("password1"))
        if commit:
            user.save()
        return user.save()


class UserChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    disabled password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'password', 'username')


"""
    Auth form with remember me
"""

class AuthForm(AuthenticationForm):
    remember_me = forms.BooleanField(label="Remeber me ", required=False, initial=False)

        

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = "__all__"
        exclude = ['user']

users/views.py
import json
from django.shortcuts import redirect, render
from users.forms import ProfileForm
from .models import Profile
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.conf import settings
from django.contrib import messages
from django.core import serializers
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your views here.

"""
    Check username and email if it's unique before registration
"""
def check_mail(request):
    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'

    if request.method == 'POST' and is_ajax:
        email = json.load(request).get("email")
        if  User.objects.filter(email=email).exists():
            return JsonResponse({"valid": True}, status=200)
        else:
            return JsonResponse({"valid": False}, status=200)
    
    return JsonResponse({"message": "Invalid request"}, status=400)

def check_username(request):
    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'

    if request.method == 'POST' and is_ajax:
        username = json.load(request).get("username")
        if  User.objects.filter(username=username).exists():
            return JsonResponse({"valid": True}, status=200)
        else:
            return JsonResponse({"valid": False}, status=200)
    
    return JsonResponse({"message": "Invalid request"}, status=400)



"""
    Authentication view: registration, sign in, sign out, closing account

"""

# sign in
def signin(request):
    if request.user.is_authenticated:
        return redirect('body:home')
    
    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'

    if request.method == 'POST' and is_ajax:
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, email=email, password=password)
        
        if user is not None:
            login(request, user)
            # if request.session.test_cookie_worked():
            #     request.session.set_expiry(31536000)
        else:
            return JsonResponse({"message":"Invalid credentials"}, status=400)

    # request.session.set_test_cookie()
    return render(request, 'users/signin.html')

# signout
@login_required
def signout(request):
    logout(request)
    return render(request, 'users/signout.html')

# account removal
@login_required
def close_account(request):
    user = User.objects.get(email=request.user.email)
    logout(request)
    user.delete()
    return render(request, 'users/close_account.html')


"""
    profile view: view profile, edit profile

"""

# edit profile details
@login_required
def edit_profile(request):
    profile = Profile.objects.get(user=request.user)
    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'

    if request.method == 'POST' and is_ajax:
        profile.user = request.user
        profile.email = request.POST['email']
        profile.username = request.POST['username']
        profile.age = request.POST['age']
        profile.gender = request.POST['gender']
        profile.save()
        return JsonResponse({"succes":"yaay ..."}, status=200)

    return JsonResponse({"error": "Invalid request method"}, status=400)
 
# view profile details
@login_required
def view_profile(request):
    profile = Profile.objects.get(user = request.user)
    form = ProfileForm(instance=profile)
    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'

    if request.method == 'GET' and is_ajax:
        profile = Profile.objects.get(user=request.user)
        serialized_profile = serializers.serialize('json', [profile,])
        return JsonResponse({"profile": serialized_profile}, status=200, safe=False)
        
    return render(request, 'users/profile.html', {"form":form}) 

templates/users/close_account.html
{% extends 'base.html' %}

{% block title %}Closed account{% endblock title %}

{% block content %}
<section class='container'>
    <p class="text-center mt-5 pt-5">Your account was closed successfully, your data won't be available in our database anymore.</p>
</section>
{% endblock content %}

{% block javascript %}
    <script>
        $(document).ready(function(){
            $("body").addClass("review")
        })
    </script>
{% endblock javascript %}

templates/users/password_change_done.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %}Password change done{% endblock title %}

{% block content %}
<section class="container">
    <p class="mt-5 pt-3">Your password was changed.</p>
</section>
{% endblock %}

{% block javascript %}
<script>
    $(document).ready(function(){
        $("body").addClass("review")

    });
</script>
{% endblock javascript %}

templates/users/password_change_form.html
{% extends "base.html" %}
{% load i18n static %}
{% load widget_tweaks %}

{% block title %}Password change form{% endblock title %}

{% block content %}
<section class='container'>
    <h3 class='text-center mt-3'>Change Password</h3>
    <div id="content-main" class='mt-5'>

        <form method="post" class='w-75'>
            {% csrf_token %}
        <div>
        {% if form.errors %}
            <p class="errornote">
            {% if form.errors.items|length == 1 %}{% translate "Please correct the error below." %}{% else %}{% translate "Please correct the errors below." %}{% endif %}
            </p>
        {% endif %}


        <p>{% translate 'Please enter your old password, for security’s sake, and then enter your new password twice so we can verify you typed it in correctly.' %}</p>

        <fieldset class="module aligned wide">

        <div class="row mb-3">
            {{ form.old_password.errors }}
            <label class="col-sm-2 fs-6 fw-bold col-form-label col-form-label-sm">Old password</label> 
            <div class="col-sm-10">
                {{ form.old_password|add_class:"form-control rounded-0" }}
            </div>
        </div>

        <div class="row mb-3">
            {{ form.new_password1.errors }}
            <label class="col-sm-2 fs-6 fw-bold col-form-label col-form-label-sm">New password</label> 
            <div class="col-sm-10">
                {{ form.new_password1|add_class:"form-control rounded-0" }}
            </div>
            {% if form.new_password1.help_text %}
            <div class="help">{{ form.new_password1.help_text|safe }}</div>
            {% endif %}
        </div>

        <div class="row mb-3">
        {{ form.new_password2.errors }}
        <label class="col-sm-2 fs-6 fw-bold col-form-label col-form-label-sm">New password confirmation</label> 
        <div class="col-sm-10">
            {{ form.new_password2|add_class:"form-control rounded-0" }}
        </div>
            {% if form.new_password2.help_text %}
            <div class="help">{{ form.new_password2.help_text|safe }}</div>
            {% endif %}
        </div>

        </fieldset>

        <div class="submit-row">
            <input type="submit" class='btn btn-sm btn-secondary px-3 fs-6 fw-bold rounded-0' value="{% translate 'Change my password' %}" class="default">
        </div>

        </div>
        </form>
    </div>
</section>

{% endblock %}

{% block javascript %}
<script>
    $(document).ready(function(){
        $("body").addClass("review")

    });
</script>
{% endblock javascript %}

templates/users/password_reset.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Password reset{% endblock title %}

{% block content %}

<section class='container mt-4'>

    <p class='text-center'>Forgotten your password? Enter your email address below, and we willl email instructions for setting a new one.</p>

    <form method="post" class="form-content">
        {% csrf_token %}
        <fieldset class="module aligned">
            <div class="form-row field-email">
                {{ form.email.errors }}
                <label for="id_email">Email address:</label>
                {{ form.email|add_class:"form-control" }}
            </div>
            <div class='d-grid gap-2 mt-3'>
                <button type="submit" class="btn-main py-1 px-3">Reset my password</button>
            </div>
        </fieldset>
    </form>
</section>
{% endblock %}

{% block javascript %}
<script>
    $(document).ready(function(){
        $("body").addClass("review")

    });
</script>
{% endblock javascript %}

templates/users/password_reset_complete.html
{% extends "base.html" %}
{% load static %}

{% block title %}Password reset complete{% endblock title %}

{% block content %}
<section class='container text-center mt-4'>

    <p>Your password has been set.  You may go ahead and log in now."</p>

    <p><a href="{% url 'users:signin' %}">Log in again</a></p>
</section>

{% endblock %}
{% block javascript %}
<script>
    $(document).ready(function(){
        $("body").addClass("review")
    });
</script>
{% endblock javascript %}

templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Password reset confirm{% endblock title %}

{% block content %}

<section class='container mt-4'>

    {% if validlink %}
     
    <h5 class='text-center'>Password reset confirmation</h5>
    <p class='text-center'>Please enter your new password twice so we can verify you typed it in correctly.</p>


    <form method="post" class="form-content">
        {% csrf_token %}
        <fieldset class="module aligned">
            <!--<input class="hidden form-control" disabled readonly autocomplete="username" value="{{ form.user.get_username }}">-->
            <div class="form-row mb-3 field-password1">
                {{ form.new_password1.errors }}
                <label for="id_new_password1">New password:</label>
                {{ form.new_password1|add_class:"form-control" }}
            </div>
            <div class="form-row mb-3 field-password2">
                {{ form.new_password2.errors }}
                <label for="id_new_password2">Confirm password:</label>
                {{ form.new_password2|add_class:"form-control" }}
            </div>
            <div class='d-grid gap-2'>
                <button type="submit" class="btn-main py-1 px-3">Change my password</button>
            </div>
        </fieldset>
    </form>
        
    {% else %}
    
    <p class='text-center'>The password reset link was invalid, possibly because it has already been used.  
        Please request a new password reset.</p>
    
    {% endif %}
</section>

{% endblock %}

{% block javascript %}
<script>
    $(document).ready(function(){
        $("body").addClass("review")
    });
    $(".form-content").submit(function(e){
        $(".main-btn").text("Changing")
    })
</script>
{% endblock javascript %}

templates/users/password_reset_done.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Password reset done{% endblock title %}

{% block content %}

<section class='container text-center mt-4'>


    <p>We have emailed you instructions for setting your password, 
    if an account exists with the email you entered. You should receive them shortly.
    </p>

    <p>If you don't receive an email, please make sure you've entered the address you registered with, 
    and check your spam folder.</p>
</section>

{% endblock %}

{% block javascript %}
<script>
    $(document).ready(function(){
        $("body").addClass("review")

    });
</script>
{% endblock javascript %}

templates/users/password_reset_email.html
{% load widget_tweaks %}

Track Bodycount

You asked for password reset for email {{ email }}.
Click the link below to be able to reset your password:
{{ protocol}}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

Thank you, see you around.

templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Profile{% endblock title %}

{% block content %}
<section class="container m-5">
    <div class="card w-75">
        <div class="card-body">
          <h5 class="card-title text-center fs-3 mb-3">Profile</h5>
          <p class="card-text text-muted fw-bold fs-4">Email :- <span id="email" ></span></p>
          <p class="card-text text-muted fw-bold fs-4">Username:- <span id="username" ></span></p>
          <p class="card-text text-muted fw-bold fs-4">Age:- <span id="age" ></span></p>
          <p class="card-text text-muted fw-bold fs-4">Gender:- <span id="gender" ></span></p>
          <!-- <p class="card-text text-muted fw-bold fs-4">Joined:- <span id="gender" ></span></p> -->


          <button class="btn btn-sm btn-link mb-3" data-bs-toggle="collapse" data-bs-target="#updateProfile" aria-expanded="false" aria-controls="updateProfile">
              Update profile
         </button>

            <div class="collapse" id="updateProfile">
                <div class="card card-body">
                    <form  method='post' action="" id="form" >
                        {% csrf_token %}
                        <div class="row mb-3">
                            <label class="col-sm-2 col-form-label">Email</label>
                            <div class="col-sm-10">
                            {{form.email|add_class:"form-control"}}                                
                            </div>
                        </div>
                        <div class="row mb-3">
                            <label class="col-sm-2 col-form-label">Username</label>
                            <div class="col-sm-10">
                            {{form.username|add_class:"form-control"}}
                            </div>
                        </div>
                        <div class="row mb-3">
                            <label class="col-sm-2 col-form-label">Age</label>
                            <div class="col-sm-10">
                                {{form.age|add_class:'form-control'}}                                  
                            </div>
                        </div>
                        <div class="row mb-3">
                            <label class="col-sm-2 col-form-label">Gender</label>
                            <div class="col-sm-10">
                                {{form.gender|add_class:"form-control form-select"}}
                            </div>
                        </div>
                        <button type="submit" id='post' class="btn rounded-0 btn-primary py-1 px-3 mt-3">Post</button>   
                    </form>
                </div>
            </div>
        </div>
    </div>
    </section>
{%  endblock content %}

{%  block javascript %}
<script>
    $(document).ready(function(){
        $("body").addClass("review")
        $("#email").text("......................");
        $("#username").text("................");
        $("#age").text(".......");
        $("#gender").text("............");

            // get coookies
            function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getCookie('csrftoken');
        
        $.ajax({
            url:"{% url 'users:view_profile' %}",
            type: "GET",
            processData: false,
            contentType: false,
            headers: {
                "X-Requested-With": "XMLHttpRequest",
                'X-CSRFToken': csrftoken
            },
            success: (response)=> {
                const prof = JSON.parse(response.profile)[0].fields
                $("#email").text(prof.email);
                $("#username").text(prof.username);
                $("#age").text(prof.age);
                $("#gender").text(prof.gender);


            },
            error: (error)=> {
                console.log(error.message)
            }
        })
    })

     // on submit call this function
    $("#form").submit(function(e){
        e.preventDefault();

        const data = new FormData($(this).get(0));
        // get coookies
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getCookie('csrftoken');

        $.ajax({
            type: "POST",
            url: "{% url 'users:edit_profile' %}",
            processData: false,
            contentType: false,
            data: data,
            headers: {
                "X-Requested-With": "XMLHttpRequest",
                'X-CSRFToken': csrftoken
            },
            success: (response)=>{
                console.log('am ready to suffer')
                $("#updateProfile").collapse("hide")
            },
            error: (error)=> {
                console.log("failed")
            }
        });
    });
</script>
{%  endblock javascript %}

templates/users/signin.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Sign in{% endblock title %}

{% block content %}
<section class='container'>

    <div aria-live="polite" aria-atomic="true" class="position-relative">
        <div class="toast-container position-absolute top-0 end-0 p-3">      
          <!-- Then put toasts within -->
        <div class="toast align-items-center" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="d-flex">
              <div class="toast-body"></div>
              <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
        </div>

        </div>
    </div>

    <form action="" class="form-content mt-4" id="form">
        {% csrf_token %}
        <p class="text-center m-0 py-2 fs-4 fw-bold mb-3">Welcome Back</p>
        <div>
            <label for="email">Email</label>
            <input class="form-control" type="email" name="email" placeholder="Email address">
        </div>
        
        <div>
            <label for="password">Password</label>
            <input class="form-control" type="password" name="password" placeholder='password'>
        </div>

        <div class='d-grid gap-2 mt-3'>
            <button type="submit" id='submit' class="btn-main py-1 px-3">Sign In</button>
        </div>
    </form>
    <p class="text-center mt-3">Forgot password ? <a href="{% url 'users:password_reset' %}">reset password</a></p>
    <p class="text-center mt-3">New here ? <a href="{% url 'body:welcome' %}">register</a></p>

</section>
{% endblock content %}

{% block javascript %}
<script>
    // doc ready function
    $(document).ready(function(){
        $("body").addClass('review')
        $("#nav-signin").addClass('active')

    })
    // submit function

    $("#form").submit(function(e){
        e.preventDefault();

        let data = new FormData($(this).get(0))
        $("#submit").text("Hold up  ...")
        $("#submit").prop("disabled", true)


        // get coookies
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getCookie('csrftoken');
        
        $.ajax({
            url:"{% url 'users:signin' %}",
            type: "POST",
            processData: false,
            contentType: false,
            headers: {
                "X-Requested-With": "XMLHttpRequest",
                'X-CSRFToken': csrftoken
            },
            data: data,
            success: (response)=> {
                console.log(response.message)
                window.location.href = "{% url 'body:home' %}"
            },
            error: (error)=> {
                const msg = error.responseJSON.message
                
                $("#submit").text("Sign In")
                $("#submit").prop("disabled", false)
                $(".toast-body").text(msg)
                $(".toast").toast("show")
            }
        })
    })
</script>
{% endblock javascript %}

templates/users/signout.html
{% extends 'base.html' %}

{% block title %}Signed out{% endblock title %}

{% block content %}
<section class='container'>
    <p class="text-center mt-5 pt-5">sign in again  ? <a href="{% url 'users:signin' %}">sign in</a></p>
</section>
{% endblock content %}

{% block javascript %}
    <script>
        $(document).ready(function(){
            $("body").addClass("review")
        })
    </script>
{% endblock javascript %}

templates/users/signup.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
<section class="container">
    <form action="{% url 'users:registration' %}" method='post' id="signup">
        {% csrf_token %}
        <p class="text-center m-0 py-2">Create account</p>
        <div class="content">
            <div >
                <label for="username">Username</label>
                {% comment %} <input type="text" placeholder=" create username" name="username"> {% endcomment %}
                {{ form.username|add_class:"form-control"}}
            </div>
            
            <div >
                <label for="email">Email</label>
                {% comment %} <input type="email" placeholder="type your email" name="email"> {% endcomment %}
                {{ form.email|add_class:"form-control"}}
            </div>
            
            <div >
                <label for="password1">Password</label>
                {% comment %} <input type="password" placeholder="type your password" name="password1"> {% endcomment %}
                {{ form.password1|add_class:"form-control"}}
            </div>

            <div >
                <label for="password2">Confirm Password</label>
                {% comment %} <input type="password" placeholder="type your password" name="password2"> {% endcomment %}
                {{ form.password2|add_class:"form-control"}}
            </div>

            <button type="submit" class="my-btn-fill py-1 px-3">Sign Up</button>
        </div>
    </form>
    
    <p class='text-center'>have an account <a href="{% url 'users:signin' %}">login</a></p>
</section>
{% endblock content %}